module.exports = {
  testEnvironment: 'node',
  moduleFileExtensions: [
    'ts',
    'tsx',
    'js',
  ],
  transform: { '^.+\\.tsx?$': 'ts-jest' },
  testRegex: [
    '__tests__.+\\.spec\\.ts',
  ],
  testPathIgnorePatterns: [
    '/.git/',
    '/.idea/',
    '/.run/',
    '/_misc/',
    '/_tmp/',
    '/lib/',
    '/coverage/',
    '/config/',
    '/dist/',
    '/node_modules/',
    '/test/',
    '/tmp/',
  ],
  globals: { 'ts-jest': { tsconfig: 'tsconfig.json' } },
  testSequencer: '<rootDir>/__tests__/setup/test-sequencer.js',
  globalSetup: '<rootDir>/__tests__/setup/global-setup.ts',
  globalTeardown: '<rootDir>/__tests__/setup/global-teardown.ts',
  testTimeout: 100_000,
};
